### ISSUE TITLE
监控 之 概要设计

### ISSUE THREAD

**Issue by AceBear** [InCar/methane#10]
## Requirement
+ 实现一个网站，查看消息计数 ( ref #2 )
+ 通过 ( ref #6 #9 ) 实现功能

## Task
+ 仅仅只做设计,暂不要实现
+ 用图片描述关键页面样式
+ 用最精炼的文字描述设计思想&要点

**Comment by ALiXiaolan** [comment]
![image](https://user-images.githubusercontent.com/26586478/71653990-3f4cc300-2d6a-11ea-9a94-09c0ade2e5bf.png)
