### ISSUE TITLE
网关实现说明

### ISSUE THREAD

**Issue by sunjun1** [InCar/methane#15]
### **网关代码实现**
---
### 代码说明
网关概要设计( #8 )
数据采集器接口类为Gather

- GatherMQ为从kafka中获取数据(必须实现)

- GatherTCP为从tcp中获取数据(非必须实现)

- GatherUDP为从udp中获取数据(非必须实现)

- GatherChannelMQ处理从kafka中获取到的数据(必须实现)

- GatherChannelTCP处理从tcp中获取到的数据(非必须实现)

- GatherChannelUDP处理从udp中获取到的数据(非必须实现)

- ServiceMQHandler负责发送数据到P(kafka方式)

- ServiceRPCHandler负责发送数据到P(RPC方式)

- MQListener负责监听P发送给G的消息(kafka)

- RPCListener负责监听P发送给G的消息(RPC)

**Comment by AceBear** [comment]
好歹你配个图啊

**Comment by baichangda** [comment]
## 编码步骤
1. 实现**GatherMQ**，从网关kafka中获取数据
2. 实现**GatherChannelMQ**，处理从 **步骤1** 网关中获取的数据
3. 实现**ServiceRPCHandler**，用 **步骤2**  的数据处理业务逻辑，调用rpc接口发送到业务层
