### ISSUE TITLE
模拟器之概要设计

### ISSUE THREAD

**Issue by AceBear** [InCar/methane#7]
## Reqiurement
+ 模拟器发送消息包
+ 正确内容的消息包内容符合 [HelloV.proto](https://github.com/InCar/methane-std/blob/974f8f0dae6c3496d051648218ba03560c14b468/HelloV1/HelloV.proto) 的定义
+ 模拟器可以模拟刻意错误的数据
+ 考虑以下发送方式的变种
    - 发送到Kafka消息队列
    - 发送到RocketMQ消息队列
    - 以TCP方式直接发送到网关
    - 以UDP方式直接发送到网关
    - 以gRPC方式直接发送到网关
+ 发送方式不需要运行时动态切换,仅需支持运行前按配置切换 或者 编译时选择一种 即可
+ 单个模拟器需要模拟0~N台车辆(N>0)
+ 模拟器可以支持按时间在运行时动态调整模拟的车辆数目
+ 模拟器可以调节车辆的数据发送频率(从数个毫秒一包数据 到 数十分钟一包数据 不等)
+ 多个模拟器可以同时以集群方式运行,以模拟出数百万台车辆的规模
+ 模拟器可以方便的扩展数据的生成算法(比如扩展模拟车辆运行轨迹,扩展模拟充电)
+ 模拟器可以扩展发送音频/视频数据(ref #3 )
+ 模拟器可以方便的扩展出接收下行命令,并执行相应的动作(比如服务器端下发"停止充电"，则模拟出相应的动作)
+ 模拟器可以扩展模拟数据补发(服务器返回失败或超时之后延时一段时间再重试发送)
+ 模拟器可以扩展统计功能(例如统计发总的总数据包，车辆总数，平均服务端响应延时，服务端错误计数)

## Task
+ 仅仅只做设计,暂不要实现
+ 用最精炼的文字描述设计思想&要点
+ 用一张图片描述主要的classes之间的关系(手绘,工具绘皆可)
+ 用最简洁的文字描述主要的class的职责
+ 不要涉及次要class，这是详细设计期的职责
+ 不要涉及主要class里方法定义细节(例如参数定义)，这也是详细设计期的职责，但可以描述关键方法的关键参数/关键算法/关键流程
+ 以后扩展部分可以只用说明以后从哪里扩展,本次设计扩展部分仅需简略涉及

ref #2

**Comment by baichangda** [comment]
# 模拟器概要设计
## 设计图
![QQ20200102-133945](https://user-images.githubusercontent.com/24662536/71653052-5c32c780-2d65-11ea-8da1-cf2c96c959ca.png)
## 设计说明

### 组件介绍

- 任务生成器
负责执行任务并声称下一次的任务，任务类型包括(生成模拟数据、发送数据、重发失败数据)
- 模拟数据生成器
负责生成模拟数据，接收任意参数
- 数据发送器
负责发送数据，具体实现为tcp发送器、udp发送器 ...
- 命令接收器
负责接收网关的命令并处理
- 性能指标收集器
负责采集模拟器各个环节的性能数据，包括(模拟数据条数、发送成功条数、发送失败条数、发送延时 ...)
### 运行流程介绍

1. **任务生成器**开启**模拟数据任务**，并创建下一次的**模拟数据任务**
2. **模拟数据任务**调用**模拟数据生成器**生成数据并存储到缓存**A**
3. **任务生成器**开启**数据发送任务**，并创建下一次的**数据发送任务**
4. **数据发送任务**从缓存**A**中读取数据并调用**数据发送器**发送数据
5. 根据**数据发送器**响应的结果，将发送失败的数据存储到缓存**B**，**任务生成器**开启**数据重发任务**，并创建下一次的**数据重发任务**(此步骤可根据需要停用)

### 接口设计
![QQ20200102-140843](https://user-images.githubusercontent.com/24662536/71653824-6bb40f80-2d69-11ea-8bec-b13fcdbb6674.png)
