### ISSUE TITLE
网关之概要设计

### ISSUE THREAD

**Issue by AceBear** [InCar/methane#8]
## Requirement
+ 接收模拟器发来的数据包 (ref #4 #5) (ref #7)
+ 转发给处理集群
    + 考虑 通过 消息队列 中转的方式(Kafka or RocketMQ)
    + 考虑直接通过 gRPC 发送的方式
    + 考虑扩展运行时按消息内容(流媒体 #3 /测量报告/紧急告警)分别通过不同路径中转
    + 考虑扩展运行时动态切换中转路径(例如优先gRPC直连,处理不过来产生堆积时再用消息队列中转)
+ 考虑扩展统计功能(例如统计消息包总数,中转时延,错误计数)
+ 考虑主动暂时关闭接收数据包(例如处理后端积压过多时)

## Task
+ 仅仅只做设计,暂不要实现
+ 用最精炼的文字描述设计思想&要点
+ 用一张图片描述主要的classes之间的关系(手绘,工具绘皆可)
+ 用最简洁的文字描述主要的class的职责
+ 不要涉及次要class，这是详细设计期的职责
+ 不要涉及主要class里方法定义细节(例如参数定义)，这也是详细设计期的职责，但可以描述关键方法的关键参数/关键算法/关键流程
+ 以后扩展部分可以只用说明以后从哪里扩展,本次设计扩展部分仅需简略涉及

ref #2

**Comment by sunjun1** [comment]
[概要设计.docx](https://github.com/InCar/methane/files/4025288/default.docx)

**Comment by sunjun1** [comment]
### 流程图
![流程图](https://user-images.githubusercontent.com/23693561/71806269-53aef980-30a3-11ea-8e78-a2a2a031a046.png)
### 设计说明

- 一个网关内部会有一个或者多个采集器(TCP/UDP/MQ),每个采集器内部会有一个或者多个逻辑处理器(Channel),可以针对不同的协议格式做不同的处理,网关对于处理后的数据可以通过直连(RPC)方式发送给P,也可以将数据发往MQ供P使用
### 接口设计
![image](https://user-images.githubusercontent.com/23693561/71807171-9eca0c00-30a5-11ea-81b0-dd8a8368c9b5.png)

- 数据中转方式以及根据消息内容做不同的数据中转,由Channel中的do()方法来处理

- listen()方法会根据P反馈的信息来决定采集器是否需要停止工作

- ask()方法会定时查询P的运行状态,根据查询到的结果来决定是否需要重新启动采集器
